import {Platform, StyleSheet} from 'react-native';

const colors = {
  background: '#F6F7FB',
  surface: '#FFFFFF',
  text: '#111827',
  muted: '#6B7280',
  soft: '#EEF0F4',
  brand: '#E1306C',
  accent: '#F77737',
  violet: '#7C3AED',
  blue: '#2563EB',
};

const shadow = Platform.select({
  ios: {
    shadowColor: '#111827',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.08,
    shadowRadius: 20,
  },
  android: {
    elevation: 4,
  },
  default: {},
});

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  feedContent: {
    paddingBottom: 34,
  },
  toolbar: {
    minHeight: 70,
    backgroundColor: colors.background,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 4,
    paddingBottom: 8,
  },
  logoBlock: {
    justifyContent: 'center',
  },
  toolbarLogo: {
    width: 118,
    height: 40,
    resizeMode: 'contain',
  },
  toolbarSubtitle: {
    color: '#9CA3AF',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginTop: -2,
  },
  toolbarButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 12,
  },
  iconButton: {
    width: 43,
    height: 43,
    borderRadius: 22,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    ...shadow,
  },
  messageBadge: {
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 10,
    backgroundColor: colors.brand,
    borderWidth: 1.5,
    borderColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 4,
    right: 2,
  },
  messageBadgeText: {
    color: colors.surface,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '900',
  },
  heroCard: {
    marginHorizontal: 14,
    marginTop: 4,
    marginBottom: 14,
    borderRadius: 30,
    backgroundColor: '#111827',
    padding: 18,
    overflow: 'hidden',
    ...shadow,
  },
  heroOrbOne: {
    position: 'absolute',
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: 'rgba(225, 48, 108, 0.55)',
    right: -54,
    top: -60,
  },
  heroOrbTwo: {
    position: 'absolute',
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: 'rgba(37, 99, 235, 0.42)',
    left: -38,
    bottom: -56,
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  heroEyebrow: {
    color: '#F9A8D4',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  heroTitle: {
    color: colors.surface,
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '900',
    letterSpacing: -0.8,
    maxWidth: 245,
    marginTop: 5,
  },
  heroIconBubble: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroDescription: {
    color: '#D1D5DB',
    fontSize: 13.5,
    lineHeight: 20,
    fontWeight: '600',
    marginTop: 12,
    maxWidth: 290,
  },
  heroStatsRow: {
    height: 68,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.12)',
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  heroStat: {
    flex: 1,
    alignItems: 'center',
  },
  heroStatValue: {
    color: colors.surface,
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: -0.3,
  },
  heroStatLabel: {
    color: '#D1D5DB',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 3,
  },
  heroStatDivider: {
    width: 1,
    height: 28,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  filterContent: {
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  filterChip: {
    height: 40,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
  },
  filterChipActive: {
    backgroundColor: colors.text,
    borderColor: colors.text,
  },
  filterText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '900',
    marginLeft: 7,
  },
  filterTextActive: {
    color: colors.surface,
  },
  sectionDivider: {
    height: 2,
    backgroundColor: colors.background,
  },
  hitSlop: {
    top: 10,
    bottom: 10,
    left: 10,
    right: 10,
  },
});

export default styles;
